name: Changeset Testing

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the PR'
        required: true

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest

    steps:
    - name: Open PR
      uses: actions/github-script@v6
      with:
        script: |
          console.log('Owner: ', context.repo.owner);
          console.log('Repo: ', context.repo.repo);
          github.rest.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            head: 'main',
            base: 'alpha',
          });
