name: Pull Request Action
on:
  workflow_dispatch
      
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo; 
            const head = '${{ github.ref_name }}';
            const base = 'alpha';

            const list = await github.rest.pulls.list({
              owner,
              repo,
              head,
              base
            });

            console.log('list', list);

            github.rest.pulls.create({
              title: 'Merging `${{ github.ref_name }}` to `alpha`',
              owner,
              repo,
              head,
              base,
              body: [
                '## Description',
                'There has been a conflict while trying to merge `master` to `alpha` branch.',
                'Can you please resolve the conflict and merge this PR?'
              ].join('\n')
            });

