name: Pull Request Action
on:
  workflow_dispatch
      
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            github.rest.pulls.create({
              title: 'Merging `master` to `alpha`',
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: '${{ github.ref }}',
              base: 'develop',
              body: [
                '## Description',
                'There has been a conflict while trying to merge `master` to `alpha` branch.',
                'Can you please resolve the conflict and merge this PR?'
              ].join('\n')
            });